import { Application, Request, Response, NextFunction } from 'express';
import { csrfSync } from 'csrf-sync';

const {
  csrfSynchronisedProtection
} = csrfSync({
  // retrieve the stored CSRF secret/token from the OIDC session
  getTokenFromState: (req) => {
    return req.oidc?.session?.csrfToken;
  },

  // store new token generated by csrf-sync into the OIDC session
  storeTokenInState: (req, token) => {
    if (req.oidc?.session) {
      req.oidc.session.csrfToken = token;
    }
  }
});

export class Csrf {
  public enableFor(app: Application): void {
    app.use(csrfSynchronisedProtection);

    app.use((req: Request, res: Response, next: NextFunction) => {
      try {
        const token = req.csrfToken();
        if (token) res.locals.csrfToken = token;
        next();
      } catch (err) {
        next(err);
      }
    });
  }
}