useCSRFProtection: true,
security:
  referrerPolicy: 'origin'
appInsights:
    instrumentationKey: false
port: 3100
services:
  name: 'IDAM User Dashboard'
  idam:
    url:
      public: 'https://idam-web-public.aat.platform.hmcts.net'
      api: 'https://idam-api.aat.platform.hmcts.net'
    endpoint:
      authorization: '/o/authorize'
      token: '/o/token'
      endSession: '/o/endSession'
    clientID: 'idam_user_dashboard'
    clientSecret: 'idam_user_dashboard_secret'
    callbackURL: 'http://localhost:3100/oauth2/callback'
    scope: 'openid profile roles manage-user search-user'
    responseType: 'code'
session:
  secret: 'local'
  redis:
    host:
    port:
    key:
health:
  timeout: 5000
  deadline: 15000
launchdarkly:
  sdkKey:
