useCSRFProtection: true,
security:
  referrerPolicy: 'origin'
appInsights:
  instrumentationKey: false
port: 3100
services:
  name: 'IDAM User Dashboard'
  idam:
    url:
      public: 'https://idam-web-public.aat.platform.hmcts.net'
      api: 'https://idam-api.aat.platform.hmcts.net'
      testingSupportApi: 'https://idam-testing-support-api.aat.platform.hmcts.net'
      dashboard: 'http://localhost:3100'
    endpoint:
      authorization: '/o/authorize'
      token: '/o/token'
      endSession: '/o/endSession'
      invite: '/api/v2/invitations'
      services: '/api/v2/services'
    systemUser:
      username: 'idam-user-dashboard-system-user@user.idam'
      password: 'Pa55word11'
    clientID: 'idam_user_dashboard'
    clientSecret: 'idam_user_dashboard_secret'
    callbackURL: 'http://localhost:3100/oauth2/callback'
    scope: 'openid profile roles manage-user search-user create-user'
    backendServiceScope: 'create-invitation view-service-provider'
    responseType: 'code'
session:
  secret: 'local'
  cookie:
    name: 'idam-user-dashboard-session'
  redis:
    host:
    port:
    key:
health:
  timeout: 5000
  deadline: 15000
RBAC:
  access: 'idam-user-dashboard--access'
featureFlags:
  launchdarkly:
    ldUser: 'idam-user-dashboard'
    sdkKey:
  flags:   # add feature-flag overrides below
providers:
  azure:
    internalName: 'azure'
    externalName: 'eJudiciary.net'
    idFieldName: 'eJudiciary User ID'
  moj:
    internalName: 'moj'
    externalName: 'MOJ/Justice.gov.uk'
    idFieldName: 'MOJ User ID'
