useCSRFProtection: true,
security:
  referrerPolicy: 'origin'
appInsights:
  connectionString: false
port: 3100
services:
  name: 'IDAM User Dashboard'
  insightname: 'idam-user-dashboard'
  idam:
    url:
      public: 'https://idam-web-public.aat.platform.hmcts.net'
      api: 'https://idam-api.aat.platform.hmcts.net'
      testingSupportApi: 'https://idam-testing-support-api.aat.platform.hmcts.net'
      dashboard: 'http://localhost:3100'
    endpoint:
      authorization: '/o/authorize'
      token: '/o/token'
      endSession: '/o/endSession'
      invite: '/api/v2/invitations'
      services: '/api/v2/services'
    systemUser:
      username:
      password:
    clientID: 'idam_user_dashboard'
    clientSecret: 'idam_user_dashboard_secret'
    callbackURL: 'http://localhost:3100/oauth2/callback'
    scope: 'openid profile roles manage-user search-user create-user view-user'
    backendServiceScope: 'create-invitation view-service-provider delete-user view-role manage-user search-user view-user'
    responseType: 'code'
    appointmentMap: '{ "@eJudiciary.net" : "APPOINT" }'
session:
  secret: 'LONG_RANDOM_STRING'
  cookie:
    name: 'idam_user_dashboard_session'
  redis:
    host:
    port:
    key:
health:
  timeout: 10000
  deadline: 15000
  idam:
    url:
      public:
      api:
RBAC:
  access: 'idam-user-dashboard--access'
featureFlags:
  launchdarkly:
    ldUser: 'idam-user-dashboard'
    sdkKey:
  flags:   # add feature-flag overrides below
providers:
  azure:
    internalName: 'azure'
    externalName: 'eJudiciary.net'
    idFieldName: 'eJudiciary User ID'
  moj:
    internalName: 'moj'
    externalName: 'MOJ/Justice.gov.uk'
    idFieldName: 'MOJ User ID'
accounts:
  status:
    lock:
      durationMinutes: 60