useCSRFProtection: true,
security:
  referrerPolicy: 'origin'
appInsights:
    instrumentationKey: false
port: 3100
# TODO: replace with IDAM AAT URL, and actual client ID and secret
services:
  name: 'IDAM user dashboard'
  idam:
    url:
      public: 'http://localhost:9000'
      api: 'http://localhost:7060'
    endpoint:
      authorization: '/o/authorize'
      token: '/o/token'
    clientID: 'idam_user_dashboard'
    clientSecret: 'idam_user_dashboard_secret'
    callbackURL: 'http://localhost:3100/oauth2/callback'
    scope: 'openid profile roles manage-user search-user'
    responseType: 'code'
session:
  secret: 'local'
  redis:
    host:
    key:
health:
  timeout: 5000
  deadline: 15000
